apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lab2-frontend
    spec:
      containers:
      - image: ifilyaninitmo/itdt-contained-frontend:master
        imagePullPolicy: Always
        name: lab2-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: "iskander"
        - name: REACT_APP_COMPANY_NAME
          value: "itmo"
